# -*- coding: utf-8 -*-
"""SARIMA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wu7lqsKipX6empI32sqyq1veSaf1xQwP
"""

!pip install kats

import pandas as pd
import numpy as np
import sys
import matplotlib.pyplot as plt
import warnings
from kats.consts import TimeSeriesData

df_115_1 = pd.read_csv("/content/sample_data/cam_115_preset_1.csv")
df_115_1 = df_115_1[['timestamp', 'avg_speed']]
df_115_1['avg_speed'] = df_115_1['avg_speed'].fillna(0)
df_115_1['timestamp'] = pd.to_datetime(df_115_1['timestamp'])
df_115_1.head()

df_from_series_115_1 = TimeSeriesData(time=df_115_1.timestamp, value=df_115_1.avg_speed)

df_from_series_115_1.plot(cols=['avg_speed'])

from kats.models.sarima import SARIMAModel, SARIMAParams
warnings.simplefilter(action='ignore')

params = SARIMAParams(
    p = 1, 
    d=1, 
    q=2, 
    seasonal_order=(1, 1, 0, 144),
    )

m_115_1 = SARIMAModel(data=df_from_series_115_1, params=params)

m_115_1.fit()

fcst_115_1 = m_115_1.predict(
    steps=120, 
    include_history=True
    )
fcst_115_1

m_115_1.plot()

df_visual_115_1 = pd.DataFrame(fcst_115_1)

df_visual_115_1.time = pd.to_datetime(df_visual_115_1.time)

df_visual_115_1 = df_visual_115_1[['time', 'fcst']]
df_visual_115_1

df_visual_115_1.plot(x='time', figsize=(25, 15))
plt.show()

df_65_2 = pd.read_csv("/content/sample_data/cam_65_preset_2.csv")
df_65_2 = df_65_2[['timestamp', 'avg_speed']]
df_65_2['avg_speed'] = df_65_2['avg_speed'].fillna(0)
df_65_2['timestamp'] = pd.to_datetime(df_65_2['timestamp'])
df_65_2.tail()

df_from_series_65_2 = TimeSeriesData(time=df_65_2.timestamp, value=df_65_2.avg_speed)

df_from_series_65_2.plot(cols=['avg_speed'])

m_65_2 = SARIMAModel(data=df_from_series_65_2, params=params)

m_65_2.fit()

fcst_65_2 = m_65_2.predict(
    steps=120,
    include_history=True
    )
fcst_65_2

m_65_2.plot()

df_visual_65_2 = pd.DataFrame(fcst_65_2)

df_visual_65_2.time = pd.to_datetime(df_visual_65_2.time)

df_visual_65_2 = df_visual_65_2[['time', 'fcst']]
df_visual_65_2

df_visual_65_2.plot(x='time', figsize=(25, 15))
plt.show()